### ISSUE TITLE
[Missing Functionality] Only apps of type "game" are shown

### ISSUE THREAD

**Issue by legendofmiracles** [dmadisetti/steam-tui#11]
I added a game demo some time ago to my steam account but they don't seem to show up in the menu

**Comment by dmadisetti** [comment]
Yup. This is expected behavior, but still broken at that.

DLC's are missing as well, this function needs to be generalized: https://github.com/dmadisetti/steam-tui/blob/main/src/interface.rs#L184 and have input from the user. We just filter for games right now. Thanks

**Comment by dmadisetti** [comment]
Thanks for your Nix support @legendofmiracles 

I was thinking of extending the config in step with Nix (which would address this issue). Do you know of any projects that might be worth using for reference?
