### ISSUE TITLE
Crash with UTF8 error (similar to Issue #9), fatal error when trying to run in cargo

### ISSUE THREAD

**Issue by OverseerCave** [dmadisetti/steam-tui#23]
Similar to Issue #9, steam-tui puts up a fatal error when starting it normally:

`Problem("Utf8Error { valid_up_to: 4502, error_len: Some(1) }")` 

However, when trying to run it with `cargo run 2> err` , I get another error:

`Problem("Unknown command sent [0mUsage:\n\tlogin <username> [<password>] [<Steam guard code>]\n")`

[err.txt](https://github.com/dmadisetti/steam-tui/files/6562766/err.txt)

So I tried to build it again (using `cargo build --release`) and this [happened](https://user-images.githubusercontent.com/39678649/120028411-f21f6000-bff4-11eb-9026-fc241e57677a.png)

I am using Ubuntu 21.04 over a SSH connection

Edit: I just tested this in the VM's console (no SSH involved this way) and while it didn't do stuff like in that picture, it still failed like above

**Comment by dmadisetti** [comment]
Hmm, I can look at this later tonight but can you run the unit tests to see if they break on your machine? What version of steamcmd are you using?

Also, try deleting `~/.config/steam-tui`. The login thing is strange

2> won't work since I removed the logging. I think I can hide it under a feature flag, so I might put it back in, and get you to run again.

Thanks!

**Comment by OverseerCave** [comment]
This may sound stupid, but how do I run the unit tests?

**Comment by dmadisetti** [comment]
`cargo test`
Rust is a pretty fun language to learn !

**Comment by OverseerCave** [comment]
These are the results of the [unit-test.txt](https://github.com/dmadisetti/steam-tui/files/6563803/unit-test.txt)

from what I can tell, it passed the tests

**Comment by dmadisetti** [comment]
Yeah unit tests are working. Are there any special characters in your steam username? Maybe windows line endings? What happened when you tried to delete the cache? Same problem?

Trying to think what it could be

**Comment by dmadisetti** [comment]
I think what may have happened is that you had an old version of the code, it crashed, and it got your config in a strange state.
Playing around, I also got my config into a weird state- so I wrote some code to try and fix that.
Try pulling main and rerunning?

**Comment by OverseerCave** [comment]
Success! No errors, no weirdness now!

I also ran `cargo build --release` and ran the executable and still successful!

I will now close this issue, thanks for fixing!
