### ISSUE TITLE
[Question] Does This Override Game Steam Check

### ISSUE THREAD

**Issue by seniorm0ment** [dmadisetti/steam-tui#24]
Does this override the issue of certain games checking if the game was launched from Steam, and if not attempt to launch the Steam client?
I know steam-cli mentions this as an issue.

**Comment by dmadisetti** [comment]
I haven't tested this with an extensive number of game, but you can launch a headless instance of the steam client by pressing the space bar.

Once this is pressed, we try to launch the game directly through `steamcmd`, which in turn communicates to the steam client.

This seems to work for the games I've tested, but I don't own a ton of games. Try it out and let me know!
