### ISSUE TITLE
[Feature Request] Ability to Remove Games

### ISSUE THREAD

**Issue by SmellsNice** [dmadisetti/steam-tui#27]
Currently (as far as I am aware) there is no way to remove downloaded games through steam-tui. It would be a nice addition and be really convenient.

PS: I think the aur package is a bit behind the repo so whoever maintains it might want to update it.

**Comment by dmadisetti** [comment]
Hmm, this makes sense but is also dangerous?

steamcmd does have a `app_uninstall : <appId>`, but casually hitting a button and uninstalling a game seems like a pain?
There's also no logging of the spawned threads, so no way of getting immediate feedback if an uninstall did occur (see #20).
The best way of doing this might be this might be running steam-tui with a flag, e.g. `steam-tui --dangerous` which would let you press `x` to uninstall a game.

I am also unsure whether an 'uninstall' removes files/saves/cache, or just purges whatever local database.

What were you thinking? Thoughts?

RE: PS: Yes it is. Cargo is also behind main (we now have auto-downloaded and cached images!), I'll sync everything up next big change I make.

**Comment by SmellsNice** [comment]
> Hmm, this makes sense but is also dangerous?
> 
> steamcmd does have a `app_uninstall : <appId>`, but casually hitting a button and uninstalling a game seems like a pain?
> There's also no logging of the spawned threads, so no way of getting immediate feedback if an uninstall did occur (see #20).
> The best way of doing this might be this might be running steam-tui with a flag, e.g. `steam-tui --dangerous` which would let you press `x` to uninstall a game.
> 
> I am also unsure whether an 'uninstall' removes files/saves/cache, or just purges whatever local database.
> 
> What were you thinking? Thoughts?
> 
> RE: PS: Yes it is. Cargo is also behind main (we now have auto-downloaded and cached images!), I'll sync everything up next big change I make.

I can see how just pressing a button to delete every file might be dangerous. A confirm prompt or as you said a flag to start a "dangerous" mode might be the best option.I think steamcmd just removes every folder it creates for a game but I might have to test it out. Also steamcmd has a forceinstalldir function which might be simple to implement into steam-tui if you are interested.

**Comment by dmadisetti** [comment]
I think "dangerous" is the easiest work around for now. We can always make this default in the config later and add in a confirmation prompt. I might have some time later this week to test and try out `app_uninstall`

Yep! I am aware of the `forceinstalldir`. If not default, the steam directory has to be properly set as well (see #7)

**Comment by oati** [comment]
How does steam-tui handle install progress right now?

**Comment by dmadisetti** [comment]
Shows that's it's downloading, and will show when it's done. It should show a % for install too, but I haven't seen it yet....

Relevant code:
https://github.com/dmadisetti/steam-tui/blob/a27a4ea408740d48e5c21fcb2f3899447f8fe985/src/client.rs#L134

**Comment by txrunn** [comment]
Hey, I was wondering if I could pick up this issue. It would be my first open source contribution, I would also appreciate any help with getting started.

**Comment by dmadisetti** [comment]
So you can hide games now. I think to remove games we'd still want a yes/no prompt.

So steps would be,

- Add keybinding to pick up delete key, and put into a confirmation mode
- Add keybinding for yes, no on confirmation mode
- Run a app uninstall script

At least for a first pass

**Comment by dmadisetti** [comment]
There's H to hide games, but I'm going to mark this as won't fix (unless someone adds it), cause I don't want to accidently delete my games
