### ISSUE TITLE
"Login" not working

### ISSUE THREAD

**Issue by Soullsa1** [dmadisetti/steam-tui#30]
When i open steam tui, press l and enter my name it loads but doesnt show any games/titles . Im not sure if this is an issue with the app or steamcmd but when i open steamcmd it gives me this output

Redirecting stderr to '/home/eugene/.local/share/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK

Steam>src/clientdll/compatmanager.cpp (905) : GetCompatibilityToolCommandLineInternal on dependent tool failed

:)

**Comment by Soullsa1** [comment]
NVM I logged out of steam and logged back in and it works now

**Comment by dmadisetti** [comment]
Thanks for the update, if this happens again let me know and we can try to debug it
