### ISSUE TITLE
[Feature Request] Support Goldberg Steam Emulator

### ISSUE THREAD

**Issue by JoshuaFern** [dmadisetti/steam-tui#31]
Hi, I haven't tried steam-tui yet but I like the look of it and I think I have an idea that aligns with your goals. 

There's an open source replacement for the steam_api library called [Goldberg Steam Emulator](https://gitlab.com/Mr_Goldberg/goldberg_emulator), it allows you to run most games without the Steam client at all by emulating the steamworks functions that games are looking for. 

For steam-tui to implement this feature, it would be best to allow users to configure steam-emu on a per-game basis, copying and backing up the steam_api files when it's enabled, and putting the originals back when it's disabled.

Also I should note that there's games this won't work with, as it's not a crack for games with DRM. If the game has any DRM Goldberg can not bypass it. In those cases the bare-bones steam client feature will still be useful.

**Comment by dmadisetti** [comment]
That's a nice idea.

Thoughts on usage: the prebuilt goldberg so/dll path has to be specified in the config. C-G to launch or something.
I think for pre-launch, search, find, and move the existing `.so` to `libsteam_api.so.steam` copy in a `libsteam_api.so.golberg`, and then modify the symlink accordingly.

Relevant docs:
 - https://gitlab.com/Mr_Goldberg/goldberg_emulator/-/raw/master/Readme_release.txt
 - https://doc.rust-lang.org/std/os/unix/fs/fn.symlink.html

**Comment by JoshuaFern** [comment]
Closing as this has gone stale.
