### ISSUE TITLE
Crashes shortly after start.

### ISSUE THREAD

**Issue by godofgrunts** [dmadisetti/steam-tui#33]
Shortly after starting steam-tui crashes with the following message:

`thread '<unnamed>' panicked at 'Stopping anyway.: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', src/interface.rs:288:14

note: run with \`RUST_BACKTRACE=1\` environment variable to display the backtrace.

![image](https://user-images.githubusercontent.com/338843/166471035-926a4864-3c72-4164-a5eb-9aef1fe6d3cc.png)

Running with RUST_BACKTRACE=1 give me the same message, but tell me to run with `RUST_BACKTRACE=full`.

Running with `RUST_BACKTRACE=full` give the follwing:

![image](https://user-images.githubusercontent.com/338843/166471723-87bec100-b5d4-4f2d-b0ec-dc0e5fb6848e.png)

```
ldd /usr/bin/steam-tui
	linux-vdso.so.1 (0x00007ffda5141000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb6e798e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fb6e78a6000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb6e769c000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb6e7caf000)
```

**Comment by dmadisetti** [comment]
Was this compiled from main?

**Comment by godofgrunts** [comment]
Actually it doesn't. It has a commit tag on it. I'll try recompiling from main.
