### ISSUE TITLE
[Feature Request] Hide games

### ISSUE THREAD

**Issue by Laar3** [dmadisetti/steam-tui#34]
Inside of steam-tui it shows up games which i dont own, 
![image](https://user-images.githubusercontent.com/77225642/172279197-99b71f6e-be81-44fe-afda-f91fa41d2cca.png)
This is the gameslist on steam-tui ^^ 
and this is my normal steam library vv
![image](https://user-images.githubusercontent.com/77225642/172279260-e1697ed8-0947-4b77-bbef-f1da127661d2.png)
i've made sure that the games arn't hidden or anything, i realise that you've sorta left this project alone so i understand if you don't put in the time to fix it but just thought id let you know.

**Comment by dmadisetti** [comment]
Yeahhh! Those are actually free games. I noticed the same thing, but you can actually play them. There's a flag that marks them as "free". But I thought it was almost more of a feature than a bug

**Comment by Laar3** [comment]
Lol, it would be really cool if there where a way to hide games, i might take a look at the source code and see if i can add a feature like that (ive been learning rust recently but not sure how hard it would be since ive never used rust-tui before)

**Comment by dmadisetti** [comment]
Yeah, you wouldn't have to change the tui code. Youd just need to mark the game as "Default" or something when parsing the response from steam cmd:

https://github.com/dmadisetti/steam-tui/blob/fe535c9e25bea6224bef78011cb68ffde440717d/src/interface.rs#L163

You can do a eprintln on map to see if the identifying "free" information.

Then to make the game visible, we'd change the definition of is_valid:

https://github.com/dmadisetti/steam-tui/blob/fe535c9e25bea6224bef78011cb68ffde440717d/src/interface.rs#L194

This goes somewhat closely with changes needed for https://github.com/dmadisetti/steam-tui/issues/11

**Comment by dmadisetti** [comment]
@Laar3 related: https://github.com/dmadisetti/steam-tui/pull/35

I like your keybind idea and storing ids in the config.

**Comment by Laar3** [comment]
> Yeah, you wouldn't have to change the tui code. Youd just need to mark the game as "Default" or something when parsing the response from steam cmd:
> 
> https://github.com/dmadisetti/steam-tui/blob/fe535c9e25bea6224bef78011cb68ffde440717d/src/interface.rs#L163
> 
> You can do a eprintln on map to see if the identifying "free" information.
> 
> Then to make the game visible, we'd change the definition of is_valid:
> 
> https://github.com/dmadisetti/steam-tui/blob/fe535c9e25bea6224bef78011cb68ffde440717d/src/interface.rs#L194
> 
> This goes somewhat closely with changes needed for #11
Oh cool, i've managed to remove it from the left list via filtering it out of the games_list variable in the tui code but that had wasn't removing it from the right view pane (they where desyncing so youd have one game "selected" but not really, i'm not sure what variable/vector i would have to filter it out of for it to not appear in the right list.

**Comment by Laar3** [comment]
As for pull #35 if it where me doing it yeah id probably have an `installed`  thing in the config file and store the gameid's of installed ones in there however caching does work too.
