### ISSUE TITLE
Package update: update Arch AUR package(s)

### ISSUE THREAD

**Issue by bkosowski** [dmadisetti/steam-tui#39]
Currently, AUR packages are very outdated. Please provide updated versions to https://aur.archlinux.org/packages/steam-tui.

**Comment by dmadisetti** [comment]
Thanks for the reminder. I will try to do this tonight.

**Comment by Real-Aso** [comment]
Thank you! it makes things a lot easier, was scratching my head so bad wondering why it wasn't working until seeing that it was version 0.1 lol.

**Comment by dmadisetti** [comment]
Done? Released 0.2.1 for bin and git. I'm closing this, but please report back if it doesn't work. I don't use Arch any more.

 - https://aur.archlinux.org/packages/steam-tui
 - https://aur.archlinux.org/packages/steam-tui-bin
