### ISSUE TITLE
[Crash] Not sure what happened

### ISSUE THREAD

**Issue by Krutonium** [dmadisetti/steam-tui#41]
![image](https://user-images.githubusercontent.com/3945538/182306634-194b28be-a435-4f0b-8117-cdce912165ae.png)

Just happened when logging in for the first time.

**Comment by dmadisetti** [comment]
Can you give me a version number and turn on logging?

`steam-tui 2> error.log`

**Comment by dmadisetti** [comment]
Closing without a version number, because this may have been fixed in #9 and #23
