### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by keysrun** [dmadisetti/steam-tui#48]
Hello. My question is - is it possible to somehow run and use steam-tui on windows 10. I only managed to install steamcmd. It is not clear how to start binary.

**Comment by dmadisetti** [comment]
Good question. Maybe through WSL? I will try at add a cross platform compilation target, but my first impression is that this will require some additional work

**Comment by cat00mem** [comment]
I was able to install ubuntu system on WSL. But I don't understand how to open binary steam-tui in the Ubuntu console. Tried to launch via `C:\steamcmd\steam-tui`

**Comment by cat00mem** [comment]
I tried to find on google how to run this binary file, but I found it only with files that have `.bin` at the end

**Comment by cat00mem** [comment]
I installed cargo, and tried to run the command cargo run steam-tui , like the process went, but at the end it showed errors. Attached screenshots -
![cmd_cQdbXplrmo](https://user-images.githubusercontent.com/100219626/187366612-793309e1-2cdb-413d-a37d-fed886280f76.png)
![cmd_TcyvIG9aaV](https://user-images.githubusercontent.com/100219626/187366613-87e400c9-3f1e-4063-964e-443fa89f77f9.png)

**Comment by dmadisetti** [comment]
So this is due to us using termion- which does not support linux. There is a windows patch:

```
[patch.crates-io]
termion = { git = "https://gitlab.redox-os.org/Jezza/termion.git", branch = "windows-support" }
```

and the other alternative is to use crossterm over termion (which is now the default for tui).

**Comment by cat00mem** [comment]
I moved the*crossterm library to the steamcmd folder, ran steam-tui via cargo run, and other errors showed up...

![cmd_pHvFMZifzf](https://user-images.githubusercontent.com/100219626/187539228-a4e3930f-6eac-4f64-b77b-9e58527ca73d.png)

**Comment by cat00mem** [comment]
I moved the*crossterm library to the steamcmd folder, ran steam-tui via cargo run, and other errors showed up...

![cmd_pHvFMZifzf](https://user-images.githubusercontent.com/100219626/187539524-0867896f-2d0f-4436-88f1-9569f297a804.png)

**Comment by cat00mem** [comment]
I only used the version with the crossterm library, because I don't understand how to install this patch)

**Comment by dmadisetti** [comment]
Yeah, so more needs to be done than just change the library, we have to change the code for it too. The blog I link in #50 shows some of the work required.

I don't have the bandwidth for this right now, but I think it might be a pretty simple change if you can find someone familiar with rust and tui-rs

**Comment by cat00mem** [comment]
I pasted the lines with your patch into `Cargo.toml` and it showed an error -

![cmd_LumSD8QrEx](https://user-images.githubusercontent.com/100219626/187624734-6038f6bc-9605-46ea-ab89-e076ca55bc40.png)

**Comment by cat00mem** [comment]
I ran cargo run via WSL and steam-tui started up! But immediately showed an error that steamcmd was not installed (I tried to install steamcmd for windows and for linux)

![cmd_41UNzsA6Tr](https://user-images.githubusercontent.com/100219626/187833252-03b33226-728e-47b4-ba1b-b25957bdd076.png)
![explorer_EaPfIhVmPj](https://user-images.githubusercontent.com/100219626/187833255-cc848e0d-a6c7-4133-be0c-d398978a8e69.png)

**Comment by dmadisetti** [comment]
Cool! I appreciate your dedication to getting this to work lol. You need to download steamcmd. You can see how we set up the test box here:

https://github.com/dmadisetti/steam-tui/blob/744b9841b9bc332a60741584760d4abf55fe41bf/.github/workflows/test.yml#L21-L26

(try running those lines)
But note, running through WSL will not be the same as running native. It will be linux gaming on windows. You will have to set up X windows for that: https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

I might be able to add crossterm sometime this weekend

**Comment by cat00mem** [comment]
I installed those components and steam-tui started showing my library! But now it's not clear to me how to configure X windows so that the games run.

![cmd_FVrjveEeBd](https://user-images.githubusercontent.com/100219626/187968204-85673b20-bd2b-4656-8d83-376d2b630423.png)

**Comment by dmadisetti** [comment]
Hmm, I thought I shared a blog about someone who does this: https://medium.com/geekculture/gaming-on-wsl-b367459f6977

Anyway, I am not sure if X will work with Windows 10. I will try to get crossterm working this evening, and then it should (maybe) run native windows

**Comment by cat00mem** [comment]
Unfortunately, I was unable to install the game. probably the only option is to wait for your upgraded version of crossterm.

**Comment by cat00mem** [comment]
hi, is there any success with running crossterm on windows?

**Comment by Terraphice** [comment]
Ah, what a shame. Another TUI without Windows support... 😞

**Comment by Tom60chat** [comment]
Just checked, you can built it for now.
The only issue I fixed it's to replace `KeyCode::Char('\n')`  by `KeyCode::Enter` because the Enter key would not work.

But after that I'm stuck at login, like the app was not able to pass the login command to steamcmd.exe (And I give up here)

**Comment by dmadisetti** [comment]
Do you have a branch I can see your changes @Tom60chat

**Comment by dmadisetti** [comment]
Since steam tui can run custom scripts, and cross term works- I'm going to count this as won't fix / completed- since you can just rig up your script to launch windows siide

**Comment by guihkx** [comment]
@dmadisetti Can you please consider reopening this?

While steam-tui builds just fine on Windows nowadays, I can't get past this screen:

![image](https://github.com/dmadisetti/steam-tui/assets/626206/b62e65bd-7f1e-4bf8-b87c-c8ce6d574fc9)

It looks like `steam-tui` spawns `steamcmd.exe` just fine:

![image](https://github.com/dmadisetti/steam-tui/assets/626206/04535fc5-e19a-4587-87f0-9f7b31c27c6c)

But my guess is that when `steam-tui` sends the `login` command to `steamcmd.exe`, that doesn't actually work...

I'm not a Windows programmer (though I occasionally use it for gaming), so I'm not sure how to debug this further...

**Comment by dmadisetti** [comment]
Hmm, have you never been able to get past the prompt?

Mind if we open a separate issue since Windows should technically work?

**Comment by guihkx** [comment]
>Hmm, have you never been able to get past the prompt?

This is actually my first time building and running steam-ui on Windows, but no, I have not been able to get past that prompt yet...

>Mind if we open a separate issue since Windows should technically work?

Sounds good to me, I'll do that shortly.
