### ISSUE TITLE
Migrate to Crossterm over Termion

### ISSUE THREAD

**Issue by dmadisetti** [dmadisetti/steam-tui#50]
[crossterm](https://github.com/crossterm-rs/crossterm) pros:  
 - crossterm is now the tui-rs default
 - crossterm supports windows (see #48)
 - prettier readme doc
 - more recent support than termion (Aug 21st, 2022 vs Sept 27th, 2021)

[termion](https://github.com/redox-os/termion) pros:
 - wider usage
 - less work for me

Others considering this migration (for context):
- https://github.com/kamiyaa/joshuto/issues/133

Blog on migration:
 - https://www.jntrnr.com/porting-the-pikachu/

**Comment by Zeerooth** [comment]
I'm all for migrating to crossterm, it seems to have gained more traction than termion, it's being maintained better, has better docs and of course windows support is a huge plus if steam-tui decides to support windows.
