### ISSUE TITLE
Double entries / filter by installed

### ISSUE THREAD

**Issue by Sir-Photch** [dmadisetti/steam-tui#53]
Hi!

This is a pretty cool TUI for steam, I gotta be honest.
Two things that appeared to me though:

I get multiple entries for the same game, if they are installed:
![grafik](https://user-images.githubusercontent.com/47949835/207447876-9cbbab3b-dd87-4e64-b132-2240d3eb1e73.png)

Is this an issue of your implementation?

Also, would it be possible to add a filter to only show installed games? Would make things easier for ppl with larger libraries.

I know some rust, so If you point me to the right places, I might be able to modify that myself.

Cheers!

**Comment by dmadisetti** [comment]
Does this solve your issue? https://github.com/dmadisetti/steam-tui#hiding-games

If the entries have different ida, then it's a steam thing. Let me know if they have the same id

**Comment by dmadisetti** [comment]
I saw your branch, does this seem to work?
https://github.com/Sir-Photch/steam-tui/commit/d27c561edc90fe0d18aa6764d0a74e81b8f8c197

If you create a PR I'll merge it

**Comment by Sir-Photch** [comment]
There are no duplicates anymore, but launching games does not work properly on my machine. Maybe you have a try and see if it still works for you? I am not sure whether this is a breaking change or it's just an issue with my system.
