### ISSUE TITLE
Cannot login with cargo version.  Binary version refuses to work at all.

### ISSUE THREAD

**Issue by Scary-Guy** [dmadisetti/steam-tui#54]
I see the ASCII Steam logo and a login prompt at the bottom of the screen.  When I put in my username it just hangs.

steamcmd  has been installed and I followed the steps to set that up.
openssl-dev  was also installed because Cargo complained.

When running just the standard binary, that doesn't work at all:

ldd steam-tui
	linux-vdso.so.1 (0x00007ffdfb7b5000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd452976000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd45288f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd452665000)
	/nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007fd45309f000)

Linux 5.15.0-56-generic #62-Ubuntu (Mint) SMP
8(16) AMD Threadripper 3800MHz processors, 121357.90 total bogomips, 31953M RAM
System library 2.35.0

**Comment by dmadisetti** [comment]
You're running on Mint? Weird that glibc is pointing to nix store- I'll compile future binaries on something a bit more normal.

If you have a large number of games it can take awhile to process, but there should be a progress bar. Games are cached after first load, so it won't take as long to process

**Comment by Sir-Photch** [comment]
actually, I have the same behaviour on my laptop. I do not get a progress-bar. <kbd>Ctrl+c</kbd> doesn't quit the program, it just appends the `c` to the login name. The cached version on my desktop-pc works though, since there, games are cached.

**Comment by Virusnest** [comment]
I have the same issue on my m1 mac

**Comment by bentinata** [comment]
Coming from #56.

I'm using `steamcmd` version `1685487853`.

```sh
$ steamcmd
Redirecting stderr to '/Users/bentinata/Library/Application Support/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1685487853
-- type 'quit' to exit --
Loading Steam API...OK

Steam>
```

**Comment by fred21O4** [comment]
Old issue but I had this issue today and the solution I found to not being able to login is replacing all KeyCode::Char('\n') in main.rs with KeyCode::Char('\n') | KeyCode::Enter
Works great for me after that
`sed -i "s@KeyCode::Char('\\\n')@KeyCode::Char('\\\n') | KeyCode::Enter@g" src/main.rs`
this command will replace it for you, just run cargo run after and it should be working

**Comment by dmadisetti** [comment]
This is really 2 issues-
 - 1 the unresponsiveness of the UI (fixed in A bit of a caching issue led to this as well. Pushed the fix mentioned here and tidied up the workflow in https://github.com/dmadisetti/steam-tui/commit/19cdcb2b4a5c93df0617f0258520beb673a44b31)
 - 2 The binary versions not working (which see #58 #68)
