### ISSUE TITLE
will this keep proton launch settings?

### ISSUE THREAD

**Issue by r3k2** [dmadisetti/steam-tui#57]
will this launch with the proton custom command we add to the steam client  like ENV variables etc? I am trying to launch a game that uses proton and is not launching

**Comment by dmadisetti** [comment]
Should preserve environmental variables, but launching with proton is not directly supported, but if you have it configured in Steam, have steam running in the background (press <space>), then steam-tui will use steam-cmd which should launch as if you were directly doing it from the UI.

But yeah. We should extend to for more customization. Closing this in favour of #47
