### ISSUE TITLE
Blank games list after login

### ISSUE THREAD

**Issue by proudhon** [dmadisetti/steam-tui#62]
After login my games list is blank.
I'm on version 0.2.1 installed via AUR.

**Comment by dmadisetti** [comment]
Aur in general is broken, I need to update it

**Comment by CDTay** [comment]
> Aur in general is broken, I need to update it

How do we install then? Make and Pkgmake don't seem to work

**Comment by zDEFz** [comment]
I have the same issue using just the git version of here.

**Comment by ALittlePatate** [comment]
same issue with the AUR and the git version

**Comment by abowen** [comment]
I've just started to learn Rust, so thought I'd debug the code to investigate

I haven't worked out the fix yet.

I replaced

```rust
let keys = keys_from_licenses(licenses);
```

with

```rust
let keysFull = keys_from_licenses(licenses);
let mut keys = Vec::new();
keys.push(keysFull[0]);
```

And at least some games then appeared on list.

Maybe one of those games isn't compatible / parsed properly with SteamCMD and it's failing?

I have a library of about 1,000 games (subscribed to Humble Bundle way too long), so need to find out where it's failing/timing out.

I know when reclaiming keys that Steam can rate limit you, so that's another possibility.

**Comment by JupiLogy** [comment]
@abowen 
> And at least some games then appeared on list.

This is good to hear, I have been having the same problem with no games showing up. I would love it if you could make a fork with the fix and new binaries as I don't have the tools to compile rust.

Thanks,
Jupy

**Comment by abowen** [comment]
I'm taking a shot in the dark, but seems that there's a state issue where some Steam fluff makes it's way through to loading up all the keys. I spent more time in debugger and noticed that my key list was getting cleared and added a quick filter to remove it.

```
                        ["licenses_print"] => {
                            // Extract licenses
                            if response == "[0m" {
                                continue;
                            }
```

**Comment by abowen** [comment]
Published a binary to crates.io @JupiLogy 

https://crates.io/crates/steam-tui-temp

It'll be yanked / repo deleted once a fix is merged here

**Comment by klownie** [comment]
i have the exact same issue on Nixos

**Comment by dmadisetti** [comment]
A bit of a caching issue led to this as well. Pushed the fix mentioned here and tidied up the workflow in https://github.com/dmadisetti/steam-tui/commit/19cdcb2b4a5c93df0617f0258520beb673a44b31

**Comment by zDEFz** [comment]
I would like to re-open this! I am using `steam-tui` and  it worked exactly once after re-opening the stuff a couple of times and relogging with steamcmd. Now its stuck in checking cache for forever. What should I do?

**Comment by dmadisetti** [comment]
Log back in with steamcmd? Are you running from source? I wanted to make a few more changes before cutting another release

Also try manually blowing away the cache under `~/.cache/steam-tui`. Reopening, but provide a new log if you can.

**Comment by zDEFz** [comment]
Running from source. Doing what you said does get me at LOADING... Like priorly where it worked. So I did `rm -rf ~/.cache/steam-tui` and then `steamcmd` and then `login user password` .

I tried to launch `Noita` but didn't work.
Now I exited `steam-tui` manually and opened it again.
I am at the same checking cache screen, which seemingly never ends.

**Comment by dmadisetti** [comment]
provide a log with `steam-tui 2> error.log`

Closing because it seems like the initial error was fixed. Also added custom scripts to help with executables being off
