### ISSUE TITLE
Unclear on how to launch

### ISSUE THREAD

**Issue by Jonson26** [dmadisetti/steam-tui#68]
Hello,
I am unsure on how to install/launch steam-tui. The instructions just say to "launch the binary". I tried downloading the one from the releases page, setting it as executable and running it from the shell, but all I get is a variation of "./steam-tui: not found".
My system is Kubuntu 22.04.3 LTS x86_64, by the way.

**Comment by dmadisetti** [comment]
Closing this for #58 - I need to make better binaries and will clean up the documentation
