### ISSUE TITLE
Steam-tui can't find steamcmd

### ISSUE THREAD

**Issue by riisikumi** [dmadisetti/steam-tui#69]
I'm trying to use the program on Fedora, which doesn't allow the user to install steamcmd directly from a repository. I have steamcmd installed under home/username/Steam and I've added home/username/.cargo/bin to my PATH, but I still get this error when using the steam-tui command:

Fatal Error in client thread:
An error occurred spawning the steamcmd process. Do you have it installed?
Os  { code: 2, kind: NotFound, message: "No such file or directory" }

What could the issue be?

**Comment by dmadisetti** [comment]
What happens when you have `home/username/Steam` in the path? and then launch steam-tui? If you can run steamcmd from terminal, you should be able to run steam-tui

**Comment by dmadisetti** [comment]
Closing

**Comment by kushiwushi** [comment]
To the people encountering this problem also using Fedora, I figured out a way to do it.

You need to first make sure that the folder that steamcmd and its dependencies are in your path, then rename steamcmd.sh to just steamcmd

After that, steam-tui should work.
