### ISSUE TITLE
Games aren't launching and the titles in the selection screen aren't visible (but still exist)

### ISSUE THREAD

**Issue by sweetbbak** [dmadisetti/steam-tui#71]
![shot-2024-04-28_09:39:06](https://github.com/dmadisetti/steam-tui/assets/75046310/50992c37-c4ca-4e5e-b006-dcc20df494a4)
It also reports that all of my games are not installed regardless of whether they are actually installed or not. This is with the nix-flake version. I tried it both with the nixpkgs version and with `nix profile install github:dmadisetti/steam-tui` and the same thing happens. Im on 24.05.

**Comment by dmadisetti** [comment]
I've been sitting on this because I can't repro. I think a mismatch between steamcmd could cause issues, so I updated the lock.

If you are still interested, try with `steam-tui 2> err.log` and report back

**Comment by dmadisetti** [comment]
Games not launching is a whole nother issue, steam has changed their API to a large degree

**Comment by sweetbbak** [comment]
The only thing I noticed is that when trying to launch games it tries to use `~/.steam/steam/Steamapps/common/GAME-NAME` when the actual path is `~/.steam/steam/steamapps/common/GAME-NAME` with a lower case "s" on steamapps.

err.log
```
steamcmd.sh[5126]: Restarting steamcmd by request...
prompt - "[1m\nSteam>"

...

"login" - "login"

prompt - "[1m\nSteam>"

"info" - "info"

prompt - "[1m\nSteam>"

script_path - "/home/sweet/.steam/steam/Steamapps/common/Pseudoregalia/pseudoregalia.exe"

"Tried" - "Tried"
launchable.executable - "Pseudoregalia/pseudoregalia.exe"

script_path - "/home/sweet/.steam/steam/Steamapps/common/ELDEN RING/Game/start_protected_game.exe"

"Tried" - "Tried"
launchable.executable - "ELDEN RING/Game/start_protected_game.exe"

script_path - "/home/sweet/.steam/steam/Steamapps/common/ELDEN RING/ArtbookOST/ELDEN RING Digital Artbook & Soundtrack.exe"

"Tried" - "Tried"
launchable.executable - "ELDEN RING/ArtbookOST/ELDEN RING Digital Artbook & Soundtrack.exe"

script_path - "/home/sweet/.steam/steam/Steamapps/common/ELDEN RING/AdvGuide/ELDEN RING Adventure Guide.exe"

"Tried" - "Tried"
launchable.executable - "ELDEN RING/AdvGuide/ELDEN RING Adventure Guide.exe"

```
steamcmd appears to be on version (20180104)

**Comment by dmadisetti** [comment]
Got you. You can change that with the `$STEAM_APP_DIR` env variable

**Comment by sweetbbak** [comment]
That definitely helped but its looking for a hard coded path at /sbin/ldconfig. I guess I'll try messing with the nix flake later
```
script_path - "/home/sweet/.steam/steam/steamapps/common/Pseudoregalia/pseudoregalia.exe"

path - "/home/sweet/.steam/steam/steamapps/common/Pseudoregalia/pseudoregalia.exe"

"Finding entry" - "Finding entry"

"Exits loop" - "Exits loop"

"Launching stdout:" - "Launching stdout:"
&std::str::from_utf8(&output.stdout) - Ok("")

"Launching stderr:" - "Launching stderr:"
&std::str::from_utf8(&output.stderr) - Ok("steam-runtime-identify-library-abi: Failed to execute child process \"/sbin/ldconfig\" (No such file or directory)\nrun.sh[19701]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig\nrun.sh[19701]: Warning: An unexpected error occurred while executing \"/sbin/ldconfig -XNv\", the exit status was 127\n/nix/store/sg7y7dimdfyqizfmbyv8vclypmcv05dm-bash-5.2p26/bin/bash: /lib32/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/sg7y7dimdfyqizfmbyv8vclypmcv05dm-bash-5.2p26/bin/bash)\n/nix/store/sg7y7dimdfyqizfmbyv8vclypmcv05dm-bash-5.2p26/bin/bash: /lib32/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/sg7y7dimdfyqizfmbyv8vclypmcv05dm-bash-5.2p26/bin/bash)\n")
```

**Comment by dmadisetti** [comment]
So, you might have to specify `STEAM_RUN_WRAPPER` which is just a script bundled with steam. Alternatively, `steam-run` was made specifically for this, so you could define your own entry script and tweak it

**Comment by dmadisetti** [comment]
address uninstall not showing up in #72 and will release new nixpkgs
