### ISSUE TITLE
Crash with UTF8error

### ISSUE THREAD

**Issue by alchemistswater** [dmadisetti/steam-tui#9]
Whilst building the library once logging in, it gets to about 50 something percent and then errors with this error:

Problem("Utf8Error { valid_up_to: 4502, error_len: Some(1) }")

Any ideas?

This is on arch linux, installed from the AUR with yay. I tried the steam-tui, and the steam-tui-bin just in case.

**Comment by alchemistswater** [comment]
It's possible, I took a look through my library and couldn't find anything obvious, but I have a few visual novels, so I wouldn't rule it out.
The only things I can see that look strange are a few games with the trademark symbol in the name, :tm: and at least one with an accented o, ö and a registered trademark symbol, ®.
I don't know if any of those count.

**Comment by dmadisetti** [comment]
Hmm. I tried replicating failure in unit tests, but couldn't. Do you have cargo? Can you check out that branch and run
`cargo run 2> err`

**Comment by alchemistswater** [comment]
Alright, I git cloned the repo and switched to the unicode bug branch, ran the cargo run 2> err and the result is attached. Hope it helps!
[err.txt](https://github.com/dmadisetti/steam-tui/files/6462576/err.txt)

**Comment by alchemistswater** [comment]
Nope, loaded just fine this time. No issues.

**Comment by dmadisetti** [comment]
Yeah, I think it was this: "Maxisâ¢" who is the developer of 'Spore'. Anyway, unit-test catches it now. It'll update the crate at least, but I still need to get an aur workflow setup. Cheers
